[misc]
pre_sudo = true
sudo_loop = true
assume_yes = true
cleanup = true
ask_retry = false
no_self_update = false
set_title = false
disable = ["system"]


[git]
repos = [
    "~/browser-extensions/*", 
    "~/Pictures/my-wallpapers"
]

max_concurrency = 5
arguments = "--rebase --autostash"  